### ISSUE TITLE
Do you plan to support alias config like tsconfig

### ISSUE THREAD

**Issue by viT-1** [wessberg/sass-extended-importer#1]
Just seek for CSS no-bundlers solution with aliases for @imports paths
like I solved js [with babel-plugins](https://github.com/viT-1/systemjs-babel-es6-vue/blob/6b3259cb300cebfd7bafaefff637882e607457a3/package.json#L23).

**Comment by wessberg** [comment]
Hey there. Can you be more specific? I'm not entirely sure I understand what you mean. If you ask if it supports path mapping, it sure does! In fact, one of the primary use cases of this importer is to support the `paths` property from a tsconfig. It is documented [here](https://github.com/wessberg/sass-extended-importer#path-mappingaliasing) in the README

**Comment by viT-1** [comment]
@wessberg  Thank you, now I noticed that your format is compatible with tsconfig.json format.
